<?php

/**
 * @file
 */

/**
 * Implements hook_form_node_form_alter().
 */
function octae_submissions_webform_submission_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $submit_handlers = array('Drupal\octae_submissions\Controller\WebformController::custom_submit_handler');
  $submit_handlers = array_merge($form['actions']['submit']['#submit'],$submit_handlers);
  $form['actions']['submit']['#submit'] = $submit_handlers;
}